### ISSUE TITLE
Display is blurred

### ISSUE THREAD

**Issue by bbbradsmith** [cmosher01/Epple-II#4] opened 2020-11-08 11:29 UTC
The intended display (assumed from the F8 screenshot) vs. what is seen in the program window:
![epple2_F8](https://user-images.githubusercontent.com/13027631/98463655-bb821500-218a-11eb-98d1-248d96423549.png)
![epple2_window](https://user-images.githubusercontent.com/13027631/98463657-bcb34200-218a-11eb-8d56-78a727b9615f.png)

It appears that the window is the wrong size, and the output is being bilinear stretched to 640x571, causing a vertical blurring of everything. The window does not appear to be resizeable in any way?

Switching to fullscreen doesn't help the issue, it appears to set the display to 720x576 causing blurring on both axes.

![epple2_fullscreen](https://user-images.githubusercontent.com/13027631/98463752-aa85d380-218b-11eb-8e16-bf4b63312648.png)

**Comment by cmosher01** [comment] 2022-10-30 22:28
My screenshots are not accurate.

The resolution of the image is graphically adjusted to mimic the aspect ratio of the original Apple display. The image you see when you run the program is accurate to the original hardware. Unfortunately, the aspect ratio adjustment also negatively affects the informational display as well.

**Comment by cmosher01** [comment] 2022-10-31 00:23
Duplicate of #2.

**Closed by cmosher01** 2022-10-31 00:23 UTC

**Comment by cmosher01** [comment] 2022-10-31 03:39
Note: you can try F3 for full-screen mode and see if looks any better.

**Comment by cmosher01** [comment] 2022-10-31 03:42
You can try using F2 to change from Television emulation to one of the Monitor emulations. NTSC monitors are inherently sharper than NTSC TVs.
